---
- name: Configure ec2 instance
  hosts: "{{hosts}}"
  remote_user: ubuntu
  become: yes
  gather_facts: False

  roles:
    - hostname
    - ntp
    - nginx
    - wordpress
    - mysql
    - php
    - postfix
